### ISSUE TITLE
[3.0.0-beta] query.substr is not a function

### ISSUE THREAD

**Issue by dpogue** [webpack-contrib/istanbul-instrumenter-loader#59]
Tried installing 3.0.0-beta to see if it would get rid of the parseQuery warning, and instead I'm getting this error for every file:
```
ERROR in ./src/helpers/promise.ts
Module build failed: TypeError: query.substr is not a function
    at Object.parseQuery (/Users/dpogue/Coding/project/node_modules/loader-utils/lib/parseQuery.js:12:11)
    at Object.exports.default (/Users/dpogue/Coding/project/node_modules/istanbul-instrumenter-loader/dist/index.js:17:43)
 @ ./src/helpers/promise.spec.ts 3:0-49
 @ ./src .spec.ts$
 @ ./webpack.tests.js
```

**Comment by bogdan-craciun** [comment]
Hi. I'm still getting this error, and I'm using Webpack 3.8.1, and all other packages are latest version. Is there anything I can try? Thanks.

**Comment by deguif** [comment]
Same here, I used Webpack `3.8.1`, and I got this error
```
Module build failed: TypeError: this.query.substr is not a function
    at Object.module.exports.pitch (/var/www/html/node_modules/expose-loader/index.js:43:34);
```

**Comment by d3viant0ne** [comment]
I use `istanbul-instrumenter-loader` in a few projects without issue.

For either of you still experiencing issues, we are going to need something minimal that reproduces the issue.

**Comment by alexander-akait** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!
