### ISSUE TITLE
Deprecated use of non-string passed to loaderUtils.parseQuery()

### ISSUE THREAD

**Issue by mdittmer** [webpack-contrib/istanbul-instrumenter-loader#74]
```
(node:35555) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (/path/to/node_modules/loader-utils/index.js:78:3)
    at Object.module.exports (/path/to/node_modules/istanbul-instrumenter-loader/index.js:15:35)
    at LOADER_EXECUTION (/path/to/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/path/to/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/path/to/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/path/to/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/path/to/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
    at /path/to/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
    at /path/to/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3)
```

```
> npm list istanbul-instrumenter-loader 
...
└── istanbul-instrumenter-loader@2.0.0 
```

```
> npm --version
3.10.9
```

```
> node --version
v7.2.0
```

**Comment by mdittmer** [comment]
This issue appeared to go away after

```
> npm uninstall istanbul-instrumenter-loader
> npm install --save-dev istanbul-instrumenter-loader@3.0.0
```

However, I had previously done:

```
> npm uninstall istanbul-instrumenter-loader
> npm install --save-dev istanbul-instrumenter-loader
```

Any idea why the latest release was not the default install version?

**Comment by evilebottnawi** [comment]
@mdittmer maybe `npm cache clean`? also twice check your `package.json`

**Comment by michael-ciniawsky** [comment]
`v3.0.0` should be `@latest` on npm, your cache may be corrupt. In case there are still any regressions feel free to reopen
